# Communicable, Maternal, Neonatal, and Nutritional Disease Burden (CMNN)

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.show='hide'}
# Load necessary packages
pacman::p_load(tidyverse, knitr, here,scales,kableExtra)

# Import the communicable diseases data
data_cmnn <- read_csv(here("data", "burden-of-disease-cmnn.csv"))
```

## Table of Estimates for CMNN Burden Over Time

```{r echo=FALSE}
data_cmnn %>%
  filter(Code %in% c("MWI", "ZMB", "ZWE")) %>%
  rename(DAILYS = `DALYs (Disability-Adjusted Life Years) - Communicable, maternal, neonatal, and nutritional diseases - Sex: Both - Age: Age-standardized (Rate)`) %>%
  select(Code, Year, DAILYS) %>%
  pivot_wider(names_from = Code, values_from = DAILYS) %>%
  mutate(across(-Year, ~ format(
    comma(., accuracy = 1), nsmall = 0, big.mark = ","
  ))) %>%
  kable(format = "html", escape = FALSE) %>%
  kable_styling(bootstrap_options = c("hover", "striped"),
                full_width = FALSE) 
```

## Plot Showing Trends in CMNN Burden Over Time

```{r echo=FALSE}
data_cmnn %>%
  filter(Code %in% c("MWI", "ZMB", "ZWE")) %>%
  ggplot(aes(x = Year, y = `DALYs (Disability-Adjusted Life Years) - Communicable, maternal, neonatal, and nutritional diseases - Sex: Both - Age: Age-standardized (Rate)`, group = Code, color = Code)) +
  geom_line() +
  scale_y_continuous(labels = scales::comma) +
  labs(title = "Trend of DALY Burden Over Time",
       x = "Year",
       y = "DALYs Burden (Age-standardized Rate)",
       color = "Country Code") +
  scale_color_manual(values = c("MWI" = "blue", "ZMB" = "green", "ZWE" = "red")) # Assign specific colors to each country

```


## Summary of CMNN Burden Findings

Malawi's DALY's were highest in the eealy 90's but this changed in the 2000's where  the highest was Zimabwe's.


